export default {
  userLogin: 'User login',
  passWord: 'Password',
  account: 'Phone/email/username',
  login: 'Login immediately',
  forgetPassWord: 'Forget passWord',
  noAccount: 'No account',
  register: 'Register',
  otherLogin: 'Other ways to log in',
  userRegister: 'User register',
  phone: 'Phone number',
  identifyCode: 'Identifying code',
  existAccount: 'Ixisting accounts',
  sendIdentifyCode: 'Send verification code',
  resend: 'Resend',
  back: 'Back',
  networkError: 'Network error, please re - acquire verification code',
  Verificationcodehasbeen: 'Verification code has been sent, please pay attention to view',
  Fillmobilenumber: 'Fill in the mobile number correctly',
  empty: 'Mobile number, or the password is empty',
  verificationexpired: 'The verification code is near expired and the verification code is re-acquired',
  hasbeenregistered: 'The phone number has been registered',
  Verificationinvalid: 'Verification code is invalid',
  verificationincorrect: 'The verification code is incorrect, please re-enter',
  registrationinformation: 'Fill in the registration information correctly',
  Loginfailed: 'Login failed',
  CodeLogin: 'Mobile authentication code login',
  smsCodeLogin: 'SMS verification code login',
  WeChatLogin: 'WeChat quick login',
  TaskList: 'Task List',
  Auditlist: 'Audit list',
  logout: 'Logout',
  CaptureTasks: 'Capture tasks',
  Submit: 'Submit',
  Give: 'Give',
  Taskrequirements: 'Task requirements',
  Takephoto: 'Take a photo',
  Example: 'Example',
  imagesuccessfully: 'The image was uploaded successfully',
  addpicture: 'Add a picture',
  shoot: 'Please shoot',
  Groupphotos: 'group photos',
  Tips: 'Tips',
  correspondingpicture: 'Corresponding picture',
  Gotit: 'Got it',
  Abandonment: 'Abandonment of tasks',
  currenttask: 'Determine to discard the current task',
  Uploadsucceeded: 'Upload succeeded',
  Uploadin: 'Upload in',
  notask: 'There no task at the moment! ',
  Loadingin: 'Loading in',
  sureLogout: 'Are you sure to exit',
  sure: 'Sure',
  cancel: 'Cancel',
  marktarget: 'Mark target',
  continueshrink: 'Can not continue to shrink',
  continuezoom: 'Can not continue to zoom in ',
  Boxtasks: 'Box tasks',
  pass: 'Pass',
  dismissed: 'Dismissed',
  indicatepoint: 'Indicate the point',
  Targettask: 'Target positioning tasks',
  standard: 'Radius of the cross standard',
  TargetLocationAudit: 'Target location audit',
  Step: 'Step 1th',
  requirements: 'Audit requirements',
  ReviewImg: 'Review the following images',
  dismissit: 'Check the unqualified picture and dismiss it.',
  AcquisitionAudit: 'Acquisition audit',
  Nonconforming: 'Non-conforming',
  Abandonmentin: 'Abandonment in',
  CalloutAudit: 'Property Callout audit',
  BoxAudit: 'Box audit'

}
