export default {
  userLogin: 'Login',
  passWord: 'Password',
  account: 'Phone/Email/Username',
  login: 'Login',
  forgetPassWord: 'Forget passWord',
  noAccount: 'No account',
  register: 'Create one',
  otherLogin: 'Log in with',
  userRegister: 'User register',
  phone: 'Phone number',
  identifyCode: 'Code',
  existAccount: 'This acount already exists',
  sendIdentifyCode: 'Send verification code',
  resend: 'Resend',
  back: 'Back',
  networkError: 'Network error, please resend verification code',
  Verificationcodehasbeen: 'Verification code has been sent, please wait',
  Fillmobilenumber: 'Invalid mobile number',
  empty: 'Mobile or password should not be empty',
  verificationexpired: 'The verification code expired and resend please',
  hasbeenregistered: 'The phone number has been registered',
  Verificationinvalid: 'Invalid verification code',
  verificationincorrect: 'The verification code is incorrect',
  registrationinformation: 'Please enter proper information',
  Loginfailed: 'Login failed',
  CodeLogin: 'Login with SMS code',
  smsCodeLogin: 'SMS code login',
  WeChatLogin: 'Login with Wechat',
  TaskList: 'Tasks',
  Auditlist: 'Reviews',
  logout: 'Log out',
  CaptureTasks: 'Collection Task',
  Submit: 'Submit',
  Give: 'Cancel',
  Taskrequirements: 'Task Description',
  Takephoto: 'Take photo or select from album',
  Example: 'Example',
  imagesuccessfully: 'All images uploaded successfully',
  addpicture: 'Add picture',
  shoot: 'Please submit',
  Groupphotos: 'photos',
  Tips: 'Confirm',
  correspondingpicture: 'Please upload required pictures',
  Gotit: 'Yes',
  Abandonment: 'Confirm',
  currenttask: 'Are you sure to cancel the current task?',
  Uploadsucceeded: 'Upload succeeded',
  Uploadin: 'Upload in',
  notask: 'No more task',
  Loadingin: 'Loading',
  sureLogout: 'Are you sure to exit',
  sure: 'Yes',
  cancel: 'Cancel',
  marktarget: 'Please make the mark point inside the box',
  continueshrink: 'Can not zoom out any more',
  continuezoom: 'Can not zoom in any more',
  Boxtasks: 'Box labeling task',
  pass: 'Approve',
  dismissed: 'Reject',
  indicatepoint: 'Indentify the object',
  Targettask: 'Identification Task',
  standard: 'Radius of the Cross',
  TargetLocationAudit: 'Object identification review',
  Step: 'Step',
  requirements: 'Task Description',
  ReviewImg: 'Review the following images',
  dismissit: 'Reject if any unqualified pictures.',
  AcquisitionAudit: 'Collection Review',
  Nonconforming: 'Unqualified',
  Abandonmentin: 'Cancelling',
  CalloutAudit: 'Attribute tagging review',
  BoxAudit: 'Box labeling review'

}
