export default {
  userLogin: 'user login',
  passWord: 'passWord',
  account: 'phone/email/userName',
  login: 'login immediately',
  forgetPassWord: 'forget passWord',
  noAccount: 'no account',
  register: 'register',
  otherLogin: 'other ways to log in',
  userRegister: 'user register',
  phone: 'phone number',
  identifyCode: 'identifying code',
  existAccount: 'existing accounts',
  sendIdentifyCode: 'send verification code',
  resend: 'resend',
  back: 'back',
  networkError: 'Network error, please re - acquire verification code',
  Verificationcodehasbeen: 'Verification code has been sent, please pay attention to view',
  Fillmobilenumber: 'Fill in the mobile number correctly',
  empty: 'Mobile number, or the password is empty',
  verificationexpired: 'The verification code is near expired and the verification code is re-acquired',
  hasbeenregistered: 'The phone number has been registered',
  Verificationinvalid: 'Verification code is invalid',
  verificationincorrect: 'The verification code is incorrect, please re-enter',
  registrationinformation: 'Fill in the registration information correctly'

}
