export default {
  userLogin: '用户登录',
  passWord: '密码',
  account: '手机号/邮箱/用户名',
  login: '立即登录',
  forgetPassWord: '忘记密码',
  noAccount: '还没有账号',
  register: '立即注册',
  otherLogin: '其他方式登录',
  userRegister: '用户注册',
  phone: '手机号',
  identifyCode: '验证码',
  existAccount: '已有账户',
  sendIdentifyCode: '发送验证码',
  resend: '重新发送',
  back :'返回',
  networkError: '网络错误，请重新获取验证码',
  Verificationcodehasbeen: ' 验证码已发送， 请注意查看 ',
  Fillmobilenumber: '正确填写手机号码',
  empty: '手机号，或者密码为空',
  verificationexpired: '验证码已近过期，重新获取验证码',
  hasbeenregistered: '该手机号注册过了',
  Verificationinvalid: '验证码无效',
  verificationincorrect: '验证码错误，请重新输入',
  registrationinformation: '正确填写注册信息'
}
